// <auto-generated />
using System;
using DiningPhilosophers.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiningPhilosophers.Core.Migrations
{
    [DbContext(typeof(SimulationDbContext))]
    [Migration("20251127233125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiningPhilosophers.Core.Data.ForkStateSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("ElapsedSeconds")
                        .HasColumnType("double precision");

                    b.Property<int>("ForkId")
                        .HasColumnType("integer");

                    b.Property<string>("HeldByPhilosopherName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SimulationRunId")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SimulationRunId", "Timestamp");

                    b.ToTable("ForkSnapshots");
                });

            modelBuilder.Entity("DiningPhilosophers.Core.Data.PhilosopherStateSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("ElapsedSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("LastAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MealsEaten")
                        .HasColumnType("integer");

                    b.Property<string>("PhilosopherName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SimulationRunId")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SimulationRunId", "Timestamp");

                    b.ToTable("PhilosopherSnapshots");
                });

            modelBuilder.Entity("DiningPhilosophers.Core.Data.SimulationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalForks")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPhilosophers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.ToTable("SimulationRuns");
                });

            modelBuilder.Entity("DiningPhilosophers.Core.Data.ForkStateSnapshot", b =>
                {
                    b.HasOne("DiningPhilosophers.Core.Data.SimulationRun", "SimulationRun")
                        .WithMany("ForkSnapshots")
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("DiningPhilosophers.Core.Data.PhilosopherStateSnapshot", b =>
                {
                    b.HasOne("DiningPhilosophers.Core.Data.SimulationRun", "SimulationRun")
                        .WithMany("PhilosopherSnapshots")
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("DiningPhilosophers.Core.Data.SimulationRun", b =>
                {
                    b.Navigation("ForkSnapshots");

                    b.Navigation("PhilosopherSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
